### PR TITLE
Ask for credentials separately

### PR DESCRIPTION
**Pull request by derteta**
Hi,

I created this fork since the way I'd like to work with my Simplenote credentials doesn't seem to work at the moment. I'd like to store my email/username in my `.vimrc`, but not my password. However, if I don't set `g:SimplenotePassword` the plugin always asks for both username _and_ password.

My changes to `set_cred` will ensure that only the part of the credentials is asked for that isn't specified. Please let me know if there are any problems with the changes.

@mrtazz @atomicules I'm assuming that you guys are the best people to review this PR!?

Cheers

### CODE REVIEW

**Comment by atomicules** [comment]
Hi. Thanks! I will take a look (hopefully) soon.

**Comment by atomicules** [comment]
Hi, thanks for going to the length of writing tests. How are you intending that those are run? 

Admittedly I haven't looked in detail, but I guess there is a reason why you couldn't user [Vader](https://github.com/junegunn/vader.vim)?

Apart from quibbles over the tests this looks like a good addition though.

**Comment by derteta** [comment]
Hey, thanks for having a look.

I'm not sure about running the tests automatically. It seems https://github.com/mrtazz/simplenote.py is using travis ci for that purpose. Maybe that's an option here, too? How are the Vader tests run?

I haven't used Vader for 2 reasons:
1. I have no experience with it (lame excuse, I know 😄 ).
2. My changes only affected 1 function and I strongly believe in keeping the scope of tests minimal (to keep them fast).
However, if a few Vader tests are more in line with the general consensus, I'd be happy to spend some time writing them.

**Comment by atomicules** [comment]
I've merged that in without the tests for now.

**Comment by derteta** [comment]
Great, thanks!

**Pull request merged**
